"use client";
import { useEffect, useState } from "react";
import { CalendarRange, Loader2 } from "lucide-react";
import { createClient } from "@/lib/supabaseClient";
import { resetBillingDates } from "@/lib/billingAnalytics";
const initial=resetBillingDates();
export function BillingSettingsForm(){const[name,setName]=useState("Main Credit Card");const[start,setStart]=useState(initial.startDate);const[end,setEnd]=useState(initial.endDate);const[due,setDue]=useState(initial.dueDate);const[limit,setLimit]=useState("");const[threshold,setThreshold]=useState("80");const[loading,setLoading]=useState(true);const[message,setMessage]=useState("");const[error,setError]=useState("");
useEffect(()=>{void load()},[]);async function load(){const s=createClient();const{data}=await s!.from("billing_settings").select("*").maybeSingle();if(data){setName(data.billing_cycle_name);setStart(data.billing_period_start_date);setEnd(data.billing_period_end_date);setDue(data.statement_due_date);setLimit(data.monthly_credit_limit?.toString()??"");setThreshold(data.spending_warning_threshold?.toString()??"80")}setLoading(false)}
function reset(){const d=resetBillingDates();setStart(d.startDate);setEnd(d.endDate);setDue(d.dueDate);setMessage("");setError("")}
async function save(){setError("");setMessage("");if(start>=end){setError("Billing period start must be before the end date.");return}if(limit&&Number(limit)<=0){setError("Credit limit must be positive.");return}if(Number(threshold)<1||Number(threshold)>100){setError("Warning threshold must be between 1 and 100.");return}if(due<end&&!confirm("The due date is before the billing period ends. Save anyway?"))return;setLoading(true);const s=createClient();const{data:{user}}=await s!.auth.getUser();const{error:e}=await s!.from("billing_settings").upsert({user_id:user!.id,billing_cycle_name:name.trim()||"Main Credit Card",billing_period_start_date:start,billing_period_end_date:end,statement_due_date:due,monthly_credit_limit:limit?Number(limit):null,spending_warning_threshold:threshold?Number(threshold):80,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(e)setError(e.message);else setMessage("Billing settings saved.");setLoading(false)}
return <section className="card p-6"><div className="flex items-start gap-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#e4f0e7] text-[#315e43]"><CalendarRange/></div><div className="flex-1"><h2 className="m-0 text-lg font-bold">Billing Period</h2><p className="mt-1 text-sm text-[#6f7971]">Personalize the cycle used for your next bill estimate.</p>{loading?<Loader2 className="mt-6 animate-spin"/>:<div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold sm:col-span-2">Billing cycle name<input value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-xl border border-[#dce2dd] px-4 py-3"/></label><label className="text-sm font-bold">Period start<input type="date" value={start} onChange={e=>setStart(e.target.value)} className="mt-2 w-full rounded-xl border border-[#dce2dd] px-4 py-3"/></label><label className="text-sm font-bold">Period end<input type="date" value={end} onChange={e=>setEnd(e.target.value)} className="mt-2 w-full rounded-xl border border-[#dce2dd] px-4 py-3"/></label><label className="text-sm font-bold">Statement due<input type="date" value={due} onChange={e=>setDue(e.target.value)} className="mt-2 w-full rounded-xl border border-[#dce2dd] px-4 py-3"/></label><label className="text-sm font-bold">Monthly credit limit (optional)<input type="number" min="0" step="0.01" value={limit} onChange={e=>setLimit(e.target.value)} className="mt-2 w-full rounded-xl border border-[#dce2dd] px-4 py-3"/></label><label className="text-sm font-bold sm:col-span-2">Warning threshold (%)<input type="number" min="1" max="100" value={threshold} onChange={e=>setThreshold(e.target.value)} className="mt-2 w-full rounded-xl border border-[#dce2dd] px-4 py-3"/></label><div className="flex gap-3 sm:col-span-2"><button onClick={save} className="button">Save billing settings</button><button onClick={reset} className="button secondary">Reset dates</button></div></div>}{message&&<p className="rounded-xl bg-[#edf7ef] p-3 text-sm text-[#28583a]">{message}</p>}{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}</div></div></section>}

