"use client";
import { useRef, useState } from "react";
import { CheckCircle2, FileText, Loader2, LockKeyhole, Upload } from "lucide-react";
import type { ParsedTransaction } from "@/lib/types";
import { createClient } from "@/lib/supabaseClient";

const sample = `Purchase Amount:\nCAD $42.16\nTransaction Description:\nTIM HORTONS 1234\nTransaction Date:\nJuly 10, 2026`;

export function ImportEmailBox() {
  const [text, setText] = useState(""); const [result,setResult]=useState<ParsedTransaction[]|null>(null); const [error,setError]=useState(""); const [saved,setSaved]=useState(false); const [loading,setLoading]=useState(false); const file=useRef<HTMLInputElement>(null);
  async function parse(){setLoading(true);setError("");setResult(null);try{const response=await fetch("/api/parse-email",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({emailText:text})});const data=await response.json();if(!response.ok)throw new Error(data.error);setResult(data.transactions)}catch(e){setError(e instanceof Error?e.message:"Could not parse that email.")}finally{setLoading(false)}}
  async function pick(f?:File){if(!f)return;if(!/\.(txt|eml)$/i.test(f.name)){setError("Choose a .txt or .eml file.");return}setText(await f.text());setError("");setResult(null)}
  async function save(transaction:ParsedTransaction){setLoading(true);setError("");const supabase=createClient();if(!supabase){setError("Supabase is not configured.");setLoading(false);return}const {data:{user}}=await supabase.auth.getUser();if(!user){window.location.href="/login";return}const {data:rule}=await supabase.from("merchant_rules").select("category_id").eq("match_text",transaction.rawMerchant).maybeSingle();const {error:insertError}=await supabase.from("transactions").insert({user_id:user.id,transaction_date:transaction.transactionDate,amount:transaction.amount,currency:transaction.currency,raw_merchant:transaction.rawMerchant,normalized_merchant:transaction.normalizedMerchant,category_id:rule?.category_id??null,confidence:transaction.confidence,source:transaction.source});if(insertError)setError(insertError.message);else setSaved(true);setLoading(false)}
  return <div className="mt-8 grid gap-5 xl:grid-cols-[1.4fr_.7fr]"><div className="card p-5 md:p-7"><div className="mb-3 flex items-center justify-between"><label htmlFor="email" className="font-bold">Email contents</label><button className="text-xs font-bold text-[#3e6b4f]" onClick={()=>setText(sample)}>Use a sample</button></div><textarea id="email" value={text} onChange={e=>{setText(e.target.value);setSaved(false)}} placeholder="Paste the RBC notification here…" className="min-h-[300px] w-full resize-y rounded-xl border border-[#dce2dd] bg-[#fbfcfa] p-4 text-sm leading-6 outline-none focus:border-[#47785a] focus:ring-2 focus:ring-[#dcecdf]"/><div className="mt-4 flex flex-wrap gap-3"><button className="button" onClick={parse} disabled={loading}>{loading?<Loader2 className="animate-spin" size={17}/>:<FileText size={17}/>}Parse transaction</button><input ref={file} hidden type="file" accept=".txt,.eml,text/plain,message/rfc822" onChange={e=>pick(e.target.files?.[0])}/><button className="button secondary" onClick={()=>file.current?.click()}><Upload size={17}/>Choose file</button></div>{error&&<div role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</div>}{result?.map((t,i)=><div key={i} className="mt-5 rounded-2xl border border-[#bcd7c4] bg-[#f0f8f2] p-5"><div className="flex items-center gap-2 font-bold text-[#28583a]"><CheckCircle2 size={18}/>{saved?"Transaction saved":"Transaction recognized"}</div><div className="mt-4 grid gap-4 sm:grid-cols-3"><div><div className="text-xs text-[#788279]">Merchant</div><b>{t.normalizedMerchant}</b></div><div><div className="text-xs text-[#788279]">Amount</div><b>{t.currency} ${t.amount.toFixed(2)}</b></div><div><div className="text-xs text-[#788279]">Date</div><b>{t.transactionDate??"Not found"}</b></div></div><button disabled={saved||loading} onClick={()=>save(t)} className="button mt-5 disabled:opacity-50">{saved?"Saved":"Save transaction"}</button></div>)}</div><aside className="space-y-4"><div className="card p-5"><LockKeyhole className="text-[#356348]"/><h2 className="mb-2 mt-4 text-lg font-bold">Privacy by design</h2><p className="m-0 text-sm leading-6 text-[#6f7971]">Northstar extracts the amount, date, and merchant. The raw message is not saved.</p></div><div className="card p-5"><h2 className="mt-0 text-lg font-bold">Works best when the email includes</h2><ul className="mb-0 space-y-3 pl-5 text-sm text-[#68726a]"><li>Purchase Amount</li><li>Transaction Description</li><li>Transaction Date</li></ul></div></aside></div>
}
