import type { BillingSettings, Transaction } from "./types";
const day=(value:string)=>new Date(`${value}T12:00:00`);
const iso=(value:Date)=>`${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}`;
export function getActiveBillingPeriod(settings:BillingSettings){return{startDate:settings.billingPeriodStartDate,endDate:settings.billingPeriodEndDate}}
export function getTransactionsForBillingPeriod(transactions:Transaction[],settings:BillingSettings){return transactions.filter(t=>t.transactionDate&&t.transactionDate>=settings.billingPeriodStartDate&&t.transactionDate<=settings.billingPeriodEndDate)}
export function getBillingSpend(transactions:Transaction[]){return transactions.reduce((sum,t)=>sum+t.amount,0)}
export function getDaysElapsed(startDate:string,endDate:string){const end=Math.min(day(endDate).getTime(),Date.now());return Math.max(0,Math.floor((end-day(startDate).getTime())/86400000)+1)}
export function getDaysRemaining(endDate:string){return Math.max(0,Math.ceil((day(endDate).getTime()-Date.now())/86400000))}
export function getProjectedBillAmount(currentSpend:number,startDate:string,endDate:string){const elapsed=getDaysElapsed(startDate,endDate);const total=Math.floor((day(endDate).getTime()-day(startDate).getTime())/86400000)+1;return elapsed?currentSpend/elapsed*total:currentSpend}
export function getCreditLimitUsage(currentSpend:number,creditLimit:number|null){return creditLimit?currentSpend/creditLimit*100:null}
export function generateBillingSummary(settings:BillingSettings,transactions:Transaction[]){const period=getTransactionsForBillingPeriod(transactions,settings);const spend=getBillingSpend(period);return{period,spend,count:period.length,daysElapsed:getDaysElapsed(settings.billingPeriodStartDate,settings.billingPeriodEndDate),daysRemaining:getDaysRemaining(settings.billingPeriodEndDate),projected:getProjectedBillAmount(spend,settings.billingPeriodStartDate,settings.billingPeriodEndDate),creditLimitUsage:getCreditLimitUsage(spend,settings.monthlyCreditLimit),averageDaily:spend/Math.max(getDaysElapsed(settings.billingPeriodStartDate,settings.billingPeriodEndDate),1),rangeLabel:`${day(settings.billingPeriodStartDate).toLocaleDateString("en-CA",{month:"short",day:"numeric"})} – ${day(settings.billingPeriodEndDate).toLocaleDateString("en-CA",{month:"short",day:"numeric"})}`,dueLabel:day(settings.statementDueDate).toLocaleDateString("en-CA",{month:"long",day:"numeric",year:"numeric"})}}
export function resetBillingDates(){const now=new Date();const start=new Date(now.getFullYear(),now.getMonth(),1);const end=new Date(now.getFullYear(),now.getMonth()+1,0);const due=new Date(now.getFullYear(),now.getMonth()+1,21);return{startDate:iso(start),endDate:iso(end),dueDate:iso(due)}}

