import crypto from "node:crypto";

export const GMAIL_SCOPE = "https://www.googleapis.com/auth/gmail.modify";
const required = (name: string) => { const value=process.env[name]; if(!value) throw new Error(`${name} is not configured.`); return value; };
const b64url=(value:Buffer|string)=>Buffer.from(value).toString("base64url");

export function oauthState(userId:string, subject:string){const payload=b64url(JSON.stringify({userId,subject,expires:Date.now()+10*60_000}));const signature=crypto.createHmac("sha256",required("GMAIL_TOKEN_ENCRYPTION_KEY")).update(payload).digest("base64url");return `${payload}.${signature}`}
export function readOauthState(state:string){const[payload,signature]=state.split(".");const expected=crypto.createHmac("sha256",required("GMAIL_TOKEN_ENCRYPTION_KEY")).update(payload).digest();const actual=Buffer.from(signature??"","base64url");if(actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))throw new Error("Invalid OAuth state.");const value=JSON.parse(Buffer.from(payload,"base64url").toString()) as {userId:string;subject:string;expires:number};if(value.expires<Date.now())throw new Error("OAuth request expired.");return value}
export function encryptToken(token:string){const key=crypto.createHash("sha256").update(required("GMAIL_TOKEN_ENCRYPTION_KEY")).digest();const iv=crypto.randomBytes(12);const cipher=crypto.createCipheriv("aes-256-gcm",key,iv);const encrypted=Buffer.concat([cipher.update(token,"utf8"),cipher.final()]);return [iv.toString("base64url"),cipher.getAuthTag().toString("base64url"),encrypted.toString("base64url")].join(".")}
export function decryptToken(value:string){const[iv,tag,data]=value.split(".");const key=crypto.createHash("sha256").update(required("GMAIL_TOKEN_ENCRYPTION_KEY")).digest();const decipher=crypto.createDecipheriv("aes-256-gcm",key,Buffer.from(iv,"base64url"));decipher.setAuthTag(Buffer.from(tag,"base64url"));return Buffer.concat([decipher.update(Buffer.from(data,"base64url")),decipher.final()]).toString("utf8")}
export function googleConfig(){return{clientId:required("GOOGLE_CLIENT_ID"),clientSecret:required("GOOGLE_CLIENT_SECRET"),redirectUri:process.env.GOOGLE_REDIRECT_URI||"http://localhost:3000/api/gmail/callback"}}

export async function accessToken(refreshToken:string){const config=googleConfig();const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:config.clientId,client_secret:config.clientSecret,refresh_token:refreshToken,grant_type:"refresh_token"})});const data=await response.json();if(!response.ok)throw new Error(data.error_description||"Gmail authorization expired.");return data.access_token as string}
export async function gmailFetch(token:string,path:string,init?:RequestInit){const response=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me${path}`,{...init,headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json",...init?.headers}});if(!response.ok)throw new Error(`Gmail API request failed (${response.status}).`);return response.status===204?null:response.json()}
export function messageText(payload:any):string{const decode=(data?:string)=>data?Buffer.from(data,"base64url").toString("utf8"):"";const walk=(part:any):string=>{if(part?.mimeType==="text/plain"&&part.body?.data)return decode(part.body.data);for(const child of part?.parts??[]){const value=walk(child);if(value)return value}return ""};return walk(payload)||decode(payload?.body?.data)}

