"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, Loader2, Mail, RefreshCw, Unplug } from "lucide-react";
import { BillingSettingsForm } from "@/components/BillingSettingsForm";
type Connection={connected_email:string|null;subject_filter:string;last_synced_at:string|null};
export default function SettingsPage(){const[connection,setConnection]=useState<Connection|null>(null);const[subject,setSubject]=useState("");const[loading,setLoading]=useState(true);const[syncing,setSyncing]=useState(false);const[message,setMessage]=useState("");const[error,setError]=useState("");
useEffect(()=>{void status()},[]);async function status(){const response=await fetch("/api/gmail/status");const data=await response.json();if(response.ok){setConnection(data.connection);if(data.connection)setSubject(data.connection.subject_filter)}else setError(data.error);setLoading(false)}
function connect(){if(!subject.trim()){setError("Enter the exact RBC email subject first.");return}window.location.href=`/api/gmail/connect?subject=${encodeURIComponent(subject.trim())}`}
async function sync(){setSyncing(true);setError("");setMessage("");const response=await fetch("/api/gmail/sync",{method:"POST"});const data=await response.json();if(response.ok)setMessage(`Imported ${data.imported}. Duplicates ${data.duplicates}. Failed ${data.failed}.`);else setError(data.error);setSyncing(false);await status()}
async function disconnect(){await fetch("/api/gmail/status",{method:"DELETE"});setConnection(null);setMessage("Gmail disconnected.")}
return <div className="page"><div className="eyebrow">Preferences</div><h1 className="page-title">Settings</h1><div className="mt-8 grid max-w-3xl gap-4"><BillingSettingsForm/><section className="card p-6"><div className="flex items-start gap-4"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#e4f0e7] text-[#315e43]"><Mail/></div><div className="flex-1"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="m-0 text-lg font-bold">Gmail import</h2><p className="mt-1 text-sm text-[#6f7971]">Only unread messages matching the exact subject are processed.</p></div>{connection&&<span className="pill"><CheckCircle2 size={13} className="mr-1"/>Connected</span>}</div>{loading?<Loader2 className="mt-6 animate-spin"/>:<>{connection?<div className="mt-5 rounded-xl bg-[#f4f7f4] p-4 text-sm"><b>{connection.connected_email}</b><div className="mt-1 text-[#6f7971]">Subject: {connection.subject_filter}</div><div className="mt-1 text-[#6f7971]">Last sync: {connection.last_synced_at?new Date(connection.last_synced_at).toLocaleString():"Never"}</div></div>:<label className="mt-5 block text-sm font-bold">Exact RBC email subject<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="Paste the full subject line" className="mt-2 w-full rounded-xl border border-[#dce2dd] px-4 py-3 outline-none focus:border-[#47785a]"/></label>}<div className="mt-4 flex flex-wrap gap-3">{connection?<><button onClick={sync} disabled={syncing} className="button">{syncing?<Loader2 size={16} className="animate-spin"/>:<RefreshCw size={16}/>}Sync unread messages</button><button onClick={disconnect} className="button secondary"><Unplug size={16}/>Disconnect</button></>:<button onClick={connect} className="button">Connect Gmail</button>}</div></>}</div></div>{message&&<div className="mt-4 rounded-xl bg-[#edf7ef] p-3 text-sm text-[#28583a]">{message}</div>}{error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}</section><section className="card p-6"><h2 className="mt-0 text-lg font-bold">Privacy</h2><p className="mb-0 text-sm leading-6 text-[#6f7971]">Refresh tokens are encrypted before storage. Email bodies are parsed in memory and never saved. A matching message is marked read only after its transaction is saved or identified as a duplicate.</p></section></div></div>}
