"use client";
import { FormEvent, useState } from "react";
import { CircleDollarSign, Loader2 } from "lucide-react";
import { createClient } from "@/lib/supabaseClient";

export default function LoginPage() {
  const [mode, setMode] = useState<"login"|"signup">("login");
  const [email,setEmail]=useState(""); const [password,setPassword]=useState("");
  const [error,setError]=useState(""); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setLoading(true);setError("");setMessage("");const supabase=createClient();if(!supabase){setError("Supabase environment variables are missing.");setLoading(false);return}const result=mode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(result.error)setError(result.error.message);else if(mode==="signup"&&!result.data.session)setMessage("Check your email to confirm your account, then sign in.");else window.location.href="/dashboard";setLoading(false)}
  return <main className="grid min-h-screen place-items-center bg-[#173f2b] p-5"><div className="w-full max-w-md rounded-[24px] bg-white p-7 shadow-2xl md:p-9"><div className="mb-8 flex items-center gap-3 text-xl font-extrabold"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#173f2b] text-white"><CircleDollarSign/></span>Northstar</div><div className="eyebrow">Private spending insights</div><h1 className="mb-2 mt-2 font-serif text-4xl tracking-[-.04em]">{mode==="login"?"Welcome back.":"Create your account."}</h1><p className="mb-7 text-sm leading-6 text-[#6d776f]">Your financial records are isolated with Supabase Row Level Security.</p><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-bold">Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-[#dce2dd] px-4 py-3 outline-none focus:border-[#47785a]"/></label><label className="block text-sm font-bold">Password<input required minLength={6} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-[#dce2dd] px-4 py-3 outline-none focus:border-[#47785a]"/></label>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{message&&<p className="rounded-xl bg-[#edf7ef] p-3 text-sm text-[#28583a]">{message}</p>}<button disabled={loading} className="button w-full">{loading&&<Loader2 size={17} className="animate-spin"/>}{mode==="login"?"Sign in":"Create account"}</button></form><button onClick={()=>setMode(mode==="login"?"signup":"login")} className="mt-5 w-full border-0 bg-transparent text-sm font-bold text-[#356348]">{mode==="login"?"New here? Create an account":"Already have an account? Sign in"}</button></div></main>
}
