import Link from "next/link";
import { ArrowRight, Sparkles } from "lucide-react";
import { StatCard } from "@/components/StatCard";
import { SpendingChart } from "@/components/SpendingChart";
import { TransactionTable } from "@/components/TransactionTable";
import { createClient } from "@/lib/supabaseServer";
import type { Transaction } from "@/lib/types";
import type { BillingSettings } from "@/lib/types";
import { generateBillingSummary } from "@/lib/billingAnalytics";

export const dynamic = "force-dynamic";
const money=(value:number)=>new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD"}).format(value);
const categoryName=(value:any):string|null=>Array.isArray(value)?value[0]?.name??null:value?.name??null;

export default async function DashboardPage() {
  const supabase=await createClient();
  const {data:{user}}=supabase?await supabase.auth.getUser():{data:{user:null}};
  const now=new Date(); const monthStart=new Date(now.getFullYear(),now.getMonth(),1); const weekStart=new Date(now); weekStart.setDate(now.getDate()-6);
  const {data}=supabase?await supabase.from("transactions").select("id,transaction_date,amount,currency,raw_merchant,normalized_merchant,confidence,categories(name)").order("transaction_date",{ascending:false}):{data:[]};
  const {data:billingRow}=supabase?await supabase.from("billing_settings").select("*").maybeSingle():{data:null};
  const rows=(data??[]).map((r:any)=>({...r,amount:Number(r.amount),category:categoryName(r.categories)}));
  const month=rows.filter(r=>r.transaction_date&&new Date(`${r.transaction_date}T12:00:00`)>=monthStart); const last7=rows.filter(r=>r.transaction_date&&new Date(`${r.transaction_date}T12:00:00`)>=weekStart);
  const total=month.reduce((s,r)=>s+r.amount,0); const weekTotal=last7.reduce((s,r)=>s+r.amount,0); const uncategorized=rows.filter(r=>!r.category).length;
  const categoryTotals=new Map<string,number>(); month.forEach(r=>{if(r.category)categoryTotals.set(r.category,(categoryTotals.get(r.category)??0)+r.amount)}); const biggest=[...categoryTotals].sort((a,b)=>b[1]-a[1])[0];
  const daily=new Map<string,number>(); month.forEach(r=>{if(r.transaction_date)daily.set(r.transaction_date,(daily.get(r.transaction_date)??0)+r.amount)}); const chart=[...daily].sort(([a],[b])=>a.localeCompare(b)).map(([date,amount])=>({day:new Date(`${date}T12:00:00`).toLocaleDateString("en-CA",{month:"short",day:"numeric"}),amount}));
  const transactions:Transaction[]=rows.slice(0,4).map(r=>({id:r.id,transactionDate:r.transaction_date,amount:r.amount,currency:r.currency,rawMerchant:r.raw_merchant,normalizedMerchant:r.normalized_merchant,confidence:Number(r.confidence??0),source:"rbc_email",category:r.category}));
  const allTransactions:Transaction[]=rows.map(r=>({id:r.id,transactionDate:r.transaction_date,amount:r.amount,currency:r.currency,rawMerchant:r.raw_merchant,normalizedMerchant:r.normalized_merchant,confidence:Number(r.confidence??0),source:"rbc_email",category:r.category}));
  const billing:BillingSettings|null=billingRow?{id:billingRow.id,userId:billingRow.user_id,billingCycleName:billingRow.billing_cycle_name,billingPeriodStartDate:billingRow.billing_period_start_date,billingPeriodEndDate:billingRow.billing_period_end_date,statementDueDate:billingRow.statement_due_date,monthlyCreditLimit:billingRow.monthly_credit_limit?Number(billingRow.monthly_credit_limit):null,spendingWarningThreshold:billingRow.spending_warning_threshold?Number(billingRow.spending_warning_threshold):80}:null;
  const bill=billing?generateBillingSummary(billing,allTransactions):null;
  const name=user?.email?.split("@")[0]??"there";
  return <div className="page"><div className="flex flex-wrap items-end justify-between gap-5"><div><div className="eyebrow">{now.toLocaleDateString("en-CA",{weekday:"long",month:"long",day:"numeric"})}</div><h1 className="page-title">Welcome, {name}.</h1><p className="subtitle">Here’s the shape of your spending this month.</p></div><Link href="/import" className="button">Import transactions <ArrowRight size={16}/></Link></div>
  <section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Spent this month" value={money(total)} detail={`${month.length} recorded transaction${month.length===1?"":"s"}`} tone="green"/><StatCard label="Last 7 days" value={money(weekTotal)} detail={`${last7.length} recent transaction${last7.length===1?"":"s"}`}/><StatCard label="Daily average" value={money(total/Math.max(now.getDate(),1))} detail="Calendar-day average this month"/><StatCard label="Biggest category" value={biggest?.[0]??"None yet"} detail={biggest?`${money(biggest[1])} this month`:"Categorize transactions to see this"}/></section>
  <section className="card mt-5 overflow-hidden">{bill&&billing?<div className="grid gap-6 bg-[#173f2b] p-6 text-white lg:grid-cols-[1.2fr_2fr]"><div><div className="text-xs font-extrabold uppercase tracking-[.12em] text-[#bcd0c1]">Next Bill Estimate · {billing.billingCycleName}</div><div className="mt-4 font-serif text-4xl">{money(bill.spend)}</div><p className="mb-0 text-sm leading-6 text-[#c7d7cb]">{bill.rangeLabel} · due {bill.dueLabel}</p></div><div className="grid grid-cols-2 gap-4 sm:grid-cols-4"><div><span className="text-xs text-[#bcd0c1]">Transactions</span><b className="mt-1 block text-xl">{bill.count}</b></div><div><span className="text-xs text-[#bcd0c1]">Daily average</span><b className="mt-1 block text-xl">{money(bill.averageDaily)}</b></div><div><span className="text-xs text-[#bcd0c1]">Days remaining</span><b className="mt-1 block text-xl">{bill.daysRemaining}</b></div><div><span className="text-xs text-[#bcd0c1]">Projected bill</span><b className="mt-1 block text-xl">{money(bill.projected)}</b></div>{bill.creditLimitUsage!==null&&<div className="col-span-2 sm:col-span-4"><div className="flex justify-between text-xs text-[#bcd0c1]"><span>Credit limit usage</span><b>{bill.creditLimitUsage.toFixed(0)}%</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/15"><div className={`h-full rounded-full ${bill.creditLimitUsage>=(billing.spendingWarningThreshold??80)?"bg-amber-400":"bg-[#8ac49e]"}`} style={{width:`${Math.min(bill.creditLimitUsage,100)}%`}}/></div>{bill.creditLimitUsage>=(billing.spendingWarningThreshold??80)&&<p className="mb-0 mt-2 text-xs text-amber-200">Spending is above your {billing.spendingWarningThreshold}% warning threshold.</p>}</div>}</div></div>:<div className="flex flex-wrap items-center justify-between gap-4 p-6"><div><div className="eyebrow">Next Bill Estimate</div><h2 className="mb-1 mt-2 font-serif text-2xl">Set your billing period to see what’s next.</h2><p className="m-0 text-sm text-[#6f7971]">Add statement dates and an optional credit limit.</p></div><Link href="/settings" className="button">Configure billing</Link></div>}</section>
  <section className="mt-5 grid gap-5 xl:grid-cols-[1.6fr_.8fr]"><div className="card p-5"><h2 className="m-0 text-lg font-bold">Spending rhythm</h2><p className="mt-1 text-sm text-[#7a837b]">Daily totals this month</p>{chart.length?<SpendingChart data={chart}/>:<div className="grid h-[260px] place-items-center text-sm text-[#7a837b]">Your chart will appear after your first import.</div>}</div><div className="card p-5"><div className="flex items-center gap-2 text-[#335f44]"><Sparkles size={17}/><span className="text-xs font-extrabold uppercase tracking-[.1em]">A useful signal</span></div><h2 className="mt-5 font-serif text-2xl leading-tight">{uncategorized?`${uncategorized} purchase${uncategorized===1?"":"s"} need attention.`:"Everything is categorized."}</h2><p className="text-sm leading-6 text-[#6f7971]">Categorize a merchant once and Northstar can remember it for future imports.</p>{uncategorized>0&&<Link href="/categorize" className="button secondary mt-4 w-full">Review uncategorized</Link>}</div></section>
  <section className="card mt-5"><div className="flex items-center justify-between p-5"><h2 className="m-0 text-lg font-bold">Recent activity</h2><Link className="text-sm font-bold text-[#315e43]" href="/transactions">View all</Link></div>{transactions.length?<TransactionTable transactions={transactions}/>:<div className="p-10 text-center text-sm text-[#7a837b]">No transactions yet.</div>}</section></div>;
}
